invalid_values: {}

categorical_columns:
  - ChestPainType
  - RestingECG
  - ST_Slope

numeric_columns:
  - Age
  - RestingBP
  - Cholesterol
  - MaxHR
  - Oldpeak

binary_columns:
  - Sex
  - FastingBS
  - ExerciseAngina

target_column: HeartDisease

split:
  train_size: 0.70
  val_size: 0.15
  test_size: 0.15
  random_state: 42