target_column: HeartDisease
columns:

  Age:
    dtype: int
    min: 18
    max: 100

  Sex:
    dtype: str
    allowed_values:
      - M
      - F

  ChestPainType:
    dtype: str
    allowed_values:
      - TA
      - ATA
      - NAP
      - ASY

  RestingBP:
    dtype: int
    min: 0
    max: 250

  Cholesterol:
    dtype: int
    min: 0
    max: 700

  FastingBS:
    dtype: int
    allowed_values:
      - 0
      - 1

  RestingECG:
    dtype: str
    allowed_values:
      - Normal
      - ST
      - LVH

  MaxHR:
    dtype: int
    min: 60
    max: 220

  ExerciseAngina:
    dtype: str
    allowed_values:
      - Y
      - N

  Oldpeak:
    dtype: float
    min: -3.0
    max: 10.0

  ST_Slope:
    dtype: str
    allowed_values:
      - Up
      - Flat
      - Down

  HeartDisease:
    dtype: int
    allowed_values:
      - 0
      - 1
