columns:
  age:
    dtype: int
    min: 1
    max: 120

  sex:
    dtype: int
    allowed_values: [0, 1]

  cp:
    dtype: int
    allowed_values: [0, 1, 2, 3]

  trestbps:
    dtype: int
    min: 80
    max: 200

  chol:
    dtype: int
    min: 100
    max: 600

  fbs:
    dtype: int
    allowed_values: [0, 1]

  restecg:
    dtype: int
    allowed_values: [0, 1, 2]

  thalach:
    dtype: int
    min: 60
    max: 220

  exang:
    dtype: int
    allowed_values: [0, 1]

  oldpeak:
    dtype: float
    min: 0.0
    max: 6.2

  slope:
    dtype: int
    allowed_values: [0, 1, 2]

  ca:
    dtype: int
    allowed_values: [0, 1, 2, 3]

  thal:
    dtype: int
    allowed_values: [0, 1, 2]

  target:
    dtype: int
    allowed_values: [0, 1]